# Generated by Django 5.2.4 on 2025-08-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_intern_tickets_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_tickets',
            name='Status',
            field=models.CharField(choices=[('in_progress', 'IN PROGRESS'), ('to_do', 'TO BE DONE'), ('done', 'COMPLETED')], default='in_progress', max_length=50),
        ),
    ]
