# Generated by Django 5.2.4 on 2025-08-22 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_intern_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
